---
title: "Untitled"
author: "Masoud Faridi"
date: "2024-05-01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(connection = "con",message=FALSE,comment = NA)
my_pass="8952021005"
```


## Writing SQL with R


[https://en.wikiversity.org/wiki/Database_Examples/Northwind/PostgreSQL](https://en.wikiversity.org/wiki/Database_Examples/Northwind/PostgreSQL)


[https://www.w3schools.com/sql/](https://www.w3schools.com/sql/)




## Connect R to postgresql




```{r}
library(DBI,quietly = TRUE)
library(RPostgres,quietly = TRUE)
library(dplyr,quietly = TRUE)
library(dbplyr,quietly = TRUE)
con <- dbConnect(RPostgres::Postgres(), 
                 host = "localhost",port="5432", 
                 user = "postgres", dbname ="Northwind",
                 password =my_pass )
tables<-dbListTables(con)
tables
```







## SQL SELECT Statement \small[https://www.w3schools.com/sql/sql_select.asp](https://www.w3schools.com/sql/sql_select.asp)




```{sql}
SELECT CustomerName, City FROM Customers LIMIT 3;
```
```{r}
tbl(con,"customers") %>% select(customername, city) %>% 
  head(3)
```

## show_query() 


```{r}
tbl(con,"customers") %>% select(customername, city) %>% 
  show_query()
```

$$
\begin{array}{c|c}
\text{SQL QUERY} & \text{dplyr CODE} \\
\hline
\text{SELECT * FROM customers} &\text{tbl(con,"customers")} \\
\text{SELECT customername FROM customers} & \text{tbl(con,"customers") \%>\% select(customername)} \\
\text{SELECT customername, city FROM customers} & \text{tbl(con,"customers") \%>\% select(customername, city)}
\end{array}
$$




## SQL SELECT DISTINCT Statement \small [https://www.w3schools.com/sql/sql_distinct.asp](https://www.w3schools.com/sql/sql_distinct.asp)



```{sql}
SELECT DISTINCT Country FROM Customers LIMIT 3;
```

```{r}
tbl(con,"customers") %>% distinct(country) %>% head(3)
```




### Count Distinct



```{sql}
SELECT COUNT(DISTINCT Country) FROM Customers;
```

```{r}

```



## END








